<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Debtor extends Model
{
    use HasFactory;

    protected $fillable = [
        'acc_no',
        'company_name',
        'desc2',
        'register_no',
        'address1',
        'address2',
        'address3',
        'address4',
        'post_code',
        'deliver_addr1',
        'deliver_addr2',
        'deliver_addr3',
        'deliver_addr4',
        'deliver_post_code',
        'attention',
        'phone1',
        'phone2',
        'fax1',
        'fax2',
        'area_code',
        'sales_agent',
        'debtor_type',
        'nature_of_business',
        'web_url',
        'email_address',
        'display_term',
        'credit_limit',
        'aging_on',
        'statement_type',
        'currency_code',
        'allow_exceed_credit_limit',
        'note',
        'exempt_no',
        'expiry_date',
        'price_category',
        'tax_type',
        'discount_percent',
        'detail_discount',
        'last_modified',
        'last_modified_user_id',
        'created_time_stamp',
        'created_user_id',
        'overdue_limit',
        'has_bonus_point',
        'opening_bonus_point',
        'qt_block_status',
        'so_block_status',
        'do_block_status',
        'iv_block_status',
        'cs_block_status',
        'qt_block_message',
        'so_block_message',
        'do_block_message',
        'iv_block_message',
        'cs_block_message',
        'external_link',
        'is_group_company',
        'is_active',
        'last_update',
        'contact_info',
        'account_group',
        'markup_ratio',
        'tax_register_no',
        'withholding_tax_percent',
        'calc_discount_on_unit_price',
    ];

    protected $casts = [
        'credit_limit' => 'decimal:2',
        'discount_percent' => 'decimal:6',
        'overdue_limit' => 'decimal:2',
        'opening_bonus_point' => 'decimal:2',
        'has_bonus_point' => 'boolean',
        'is_group_company' => 'boolean',
        'is_active' => 'boolean',
        'expiry_date' => 'datetime',
        'last_modified' => 'datetime',
        'created_time_stamp' => 'datetime',
        'markup_ratio' => 'decimal:6',
        'withholding_tax_percent' => 'decimal:6',
    ];
}
